djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mtg.urls")),
    path("tournament/", include("tournament.urls")),

]

mtg/urls.py
from django.urls import path

from . import views

app_name = "mtg"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("get_decks", views.get_decks, name="get_decks"),
    path("get_deck/<int:deck_id>", views.get_deck_by_id, name="get_deck_by_id"),
    path("get_results", views.get_results, name="get_results"),
    path("get_decks/<int:user_id>", views.get_decks_by_user, name="get_decks_by_user"),
    path("get_results/<int:user_id>", views.get_results_by_user, name="get_results_by_user"),
    path("get_best_n_decks", views.get_best_n_decks, name="get_best_n_decks"),
    path("get_best_n_players", views.get_best_n_players, name="get_best_n_players"),
    path("get_user/<int:user_id>", views.get_user_by_id, name="get_user"),
    path("get_logged_in_user", views.get_logged_in_user, name="get_logged_in_user"),
    path("get_best", views.get_best, name="get_best"),
    path("get_options/<str:_type>", views.get_options, name="get_options"),
    path("add_match", views.add_match, name="add_match"),
    path("add_deck", views.add_deck, name="add_deck"),
]

tournament/urls.py
from django.urls import path

from . import views

app_name = "tournament"

urlpatterns = [
    path("", views.setup, name="setup"),
    path("start", views.start, name="start"),
    path("round/<int:n_round>", views.play_round, name="play_round"),
    path("next_round", views.next_round, name="next_round"),
]

tournament/models.py
from django.core.exceptions import ValidationError
from django.db import models


# Create your models here.
class Tournament(models.Model):
    date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Tournaments"
        verbose_name = "Tournament"
        ordering = ['-date']


class Player(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class PlayerTournamentStats(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='tournament_stats')
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, blank=True, related_name='players_stats')
    points = models.IntegerField(default=0)
    match_wins = models.IntegerField(default=0)
    match_losses = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('player', 'tournament')

    def reset_stats(self):
        self.points = 0
        self.match_wins = 0
        self.match_losses = 0
        self.save()

    def __str__(self):
        return f"Name: {self.player.name}. Points: {self.points} Playing tournament: {self.tournament.id}"

    def get_rivals(self, tournament):
        rivals = PlayerTournamentStats.objects.filter(
            models.Q(matches_as_player1__player2=self, matches_as_player1__tournament=tournament)
            | models.Q(matches_as_player2__player1=self, matches_as_player2__tournament=tournament),
        ).distinct()

        return rivals

    def get_kill_death_ratio(self):
        return self.match_wins - self.match_losses

    def serialize(self):
        return {
            "id": self.id,
            "name": self.player.name,
            "points": self.points,
            "match_wins": self.match_wins,
            "KD": self.get_kill_death_ratio(),
        }


class TournamentMatch(models.Model):
    class Result(models.TextChoices):
        ABSOLUTE_WIN = "AW", "2-0"
        WIN = "WN", "2-1"
        DRAW = "DW", "1-1"
        LOSS = "LS", "1-2"
        ABSOLUTE_LOSS = "AL", "0-2"

    class Meta:
        ordering = ("-date_played", )

    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name='matches', blank=True)
    player1 = models.ForeignKey(PlayerTournamentStats, on_delete=models.CASCADE, related_name='matches_as_player1')
    player2 = models.ForeignKey(PlayerTournamentStats, on_delete=models.CASCADE, related_name='matches_as_player2')
    winner = models.ForeignKey(PlayerTournamentStats, on_delete=models.CASCADE, related_name='matches_won', blank=True, null=True)
    result = models.CharField(choices=Result.choices, default=Result.ABSOLUTE_WIN, max_length=2)
    n_round = models.IntegerField()
    active = models.BooleanField(default=True)
    date_played = models.DateTimeField(auto_now_add=True)

    def clean(self):
        """
         Ensure that:
         - A deck cannot play against itself.
         - The winner corresponds with the result.
         """
        if self.player1 == self.player2:
            raise ValidationError("A deck cannot compete against itself.")

        # If result is not DRAW, winner must be either deck1 or deck2 based on result
        if self.result == self.Result.DRAW:
            if self.winner is not None:
                raise ValidationError("There must be no winner for a draw.")
        elif self.result in [self.Result.ABSOLUTE_WIN, self.Result.WIN] and self.winner != self.player1:
            raise ValidationError("Player1 must be the winner for result 2-0 or 2-1.")
        elif self.result in [self.Result.ABSOLUTE_LOSS, self.Result.LOSS] and self.winner != self.player2:
            raise ValidationError("Player2 must be the winner for result 0-2 or 1-2.")


    def save(self, *args, **kwargs):
        if self.result in [self.Result.ABSOLUTE_WIN, self.Result.WIN]:
            self.winner = self.player1
        elif self.result in [self.Result.ABSOLUTE_LOSS, self.Result.LOSS]:
            self.winner = self.player2
        elif self.result == self.Result.DRAW:
            self.winner = None

        self.clean()

        super().save(*args, **kwargs) # We modify the save() to check the equality of decks. That's why super(), to call the father save.


    def __str__(self):
        return f"{self.player1.player.name} vs {self.player2.player.name}."


    def serialize(self):
        return {
            "id": self.id,
            "player1": self.player1.serialize(),
            "player2": self.player2.serialize(),
            "date_played": self.date_played.date(),
            "winner": self.winner.player.name if self.winner else None,
            "result": self.get_result_display(),
        }

tournament/forms.py
from django import forms

class ListPlayersForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ListPlayersForm, self).__init__(*args, **kwargs)
        for i in range(1, 9):
            self.fields[f'player{i}'] = forms.CharField(
                min_length=3,
                max_length=20,
                widget=forms.TextInput(
                    attrs={'class': 'form-control', 'placeholder': f'Player{i}'}
                )
            )


    def clean(self):
        cleaned_data = super().clean()
        players = [cleaned_data.get(f"player{i}") for i in range(1, 9)]

        player_names = [name for name in players if name]

        if len(player_names) != len(set(player_names)):
            raise forms.ValidationError("All players must have unique names")
        for name in player_names:
            if  len(name) < 3:
                raise forms.ValidationError("Names must have at least 3 characters")

tournament/views.py

from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .services import *
from .forms import ListPlayersForm


# Create your views here.
def setup(request):
    """View to set up tournament players."""
    if request.method == 'GET':
        form = get_prefilled_form()
        return render(request, 'tournament/setup.html', {'form': form})

    elif request.method == 'POST':
        form = ListPlayersForm(request.POST)
        if form.is_valid():
            get_or_create_tournament(setup=True)
            enroll_players(form.cleaned_data)
            return HttpResponseRedirect(reverse('tournament:start'))


@login_required
def start(request):
    """Starts the tournament view."""
    return render(request, "tournament/start.html")


@login_required
def play_round(request, n_round):
    """Plays a specified round, creating or retrieving matches as needed."""
    match_data, ranked_players, option_results = get_round_data(n_round)
    if n_round == 4:
        end_tournament()
        return JsonResponse({
            "ranked_players": ranked_players,
            "message": "The tournament has ended"
        })
    return JsonResponse(
        {
            "match_data": match_data,
            "ranked_players": ranked_players,
            "option_results": option_results
        },
    safe=False)


@login_required
def next_round(request):
    """Processes match results for the current round and updates player data."""
    if request.method == "POST":
        response_data = process_round_results(request)
        return JsonResponse(response_data, status=response_data.get("status_code", 200))



tournament/templates/tournament/setup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Set Up Tournament</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/tournament/css/tournament.css">
</head>
<body>
    <div class="tournament-container">
        <div class="tournament-header">
            <h1>Enter Players</h1>
            <p> All names must be unique and have at least 3 characters.</p>
        </div>

        <!-- Form for setting up the tournament -->
        <form method="post" action="{% url 'tournament:setup' %}">
            {% csrf_token %}
            {% if form.non_field_errors %} {#I am cleaning the whole form, hence non_field_errors#}
                <div class="text-danger mt-1">{{ form.non_field_errors }}</div>
            {% endif %}

            {% for field in form %}
                <div class="player-input">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger mt-1">{{ field.errors }}</div>
                    {% endif %}
                </div>
            {% endfor %}

            <button type="submit" class="submit-btn">Start Tournament</button>
        </form>
    </div>

</body>
</html>

tournament/templates/tournament/start.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
    <link rel="stylesheet" href="{% static 'tournament/css/tournament.css' %}">
</head>
<body class="tournament">
    <div id="Tournament"></div>

    <!-- Components -->
    <script type="text/babel" src="{% static 'tournament/js/components/RenderRound.jsx' %}"></script>
    <script type="text/babel" src="{% static 'tournament/js/App.jsx' %}"></script>

    <script type="text/babel">
            ReactDOM.render(<App />, document.querySelector("#Tournament"));
    </script>
</body>
</html>