djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mtg.urls")),
    path("tournament/", include("tournament.urls")),

]

mtg/urls.py
from django.urls import path

from . import views

app_name = "mtg"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("get_decks", views.get_decks, name="get_decks"),
    path("get_deck/<int:deck_id>", views.get_deck_by_id, name="get_deck_by_id"),
    path("get_results", views.get_results, name="get_results"),
    path("get_decks/<int:user_id>", views.get_decks_by_user, name="get_decks_by_user"),
    path("get_results/<int:user_id>", views.get_results_by_user, name="get_results_by_user"),
    path("get_best_n_decks", views.get_best_n_decks, name="get_best_n_decks"),
    path("get_best_n_players", views.get_best_n_players, name="get_best_n_players"),
    path("get_user/<int:user_id>", views.get_user_by_id, name="get_user"),
    path("get_logged_in_user", views.get_logged_in_user, name="get_logged_in_user"),
    path("get_best", views.get_best, name="get_best"),
    path("get_options/<str:_type>", views.get_options, name="get_options"),
    path("add_match", views.add_match, name="add_match"),
    path("add_deck", views.add_deck, name="add_deck"),
]

mtg/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models

# Create your models here.
class User(AbstractUser):

    def total_played(self):
        count = 0
        for deck in self.decks.all():
            matches = Match.objects.filter(models.Q(deck1=deck) | models.Q(deck2=deck))
            count += matches.count()
        return count

    def wins(self):
        if self.decks.count() != 0:
            wins = sum([deck.wins_count for deck in self.decks.all()])
            return wins
        return 0


    def win_ratio(self):
        if self.decks.count() != 0:
            total_win_ratio = sum([deck.win_ratio() for deck in self.decks.all()])
            avg_win_ratio = round(total_win_ratio / self.decks.count(), 1)
            return avg_win_ratio
        return 0

    def serialize(self):
        return {
            "id": self.id,
            "username": self.username,
            "total_matches": self.total_played(),
            "wins": self.wins(),
            "win_ratio": self.win_ratio()
        }


class Deck(models.Model):
    class Category(models.TextChoices):
        STANDARD = 'ST', 'Standard'
        PIONEER = 'Pp', 'Pioneer'
        MODERN = 'Mn', 'Modern'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='decks')
    name = models.CharField(max_length=20)
    category = models.CharField(max_length=2,
                                choices=Category.choices,
                                default=Category.PIONEER)

    wins_count = models.PositiveIntegerField(default=0)
    losses_count = models.PositiveIntegerField(default=0)
    total_matches_count = models.PositiveIntegerField(default=0)


    def update_stats(self):
        matches = Match.objects.filter(models.Q(deck1=self) | models.Q(deck2=self))
        self.wins_count = matches.filter(winner=self).count()
        self.losses_count = matches.exclude(winner=self).count() - matches.filter(winner=None).count()
        self.total_matches_count = matches.count()
        # self.total_matches_count = Match.objects.filter(models.Q(deck1=self) | models.Q(deck2=self)).count()
        self.save()

    def win_ratio(self):
        total = self.total_matches_count
        return 0 if total == 0 else round((self.wins_count / self.total_matches_count) * 100, 1)

    def serialize(self):
        return {
            "id": self.id,
            "name": self.name,
            "ownerId": self.user.id,
            "owner": self.user.username,
            "category": self.get_category_display(),
            "wins": self.wins_count,
            "losses": self.losses_count,
            "draws": self.total_matches_count - (self.wins_count + self.losses_count),
            "total_matches": self.total_matches_count,
            "win_ratio": self.win_ratio(),
            "rivals": [{
                "id": rival.id,
                "name": rival.name,
                "owner": {
                    "id": rival.user.id,
                    "username": rival.user.username,
                },
                "stats": self.stats_vs_rival(rival)
            } for rival in self.get_rivals()]
        }

    def get_rivals(self):
        rivals = Deck.objects.filter(
            models.Q(matches_as_deck1__deck2=self) | models.Q(matches_as_deck2__deck1=self)
        ).distinct()

        r = []
        for rival in rivals:
            win_ratio = self.stats_vs_rival(rival)["win_ratio"]
            r.append((rival, win_ratio))

        sorted_rivals = sorted(r, key=lambda x: x[1], reverse=True)

        return [rivals[0] for rivals in sorted_rivals]


    def stats_vs_rival(self, rival):
        matches = Match.objects.filter(
            models.Q(deck1=self) & models.Q(deck2=rival) | models.Q(deck1=rival) & models.Q(deck2=self)
        )
        total = matches.count()
        wins = matches.filter(winner=self).count()
        losses = matches.filter(winner=rival).count()
        draws = total - wins - losses
        return {
            "wins": wins,
            "losses": losses,
            "draws": draws,
            "total": total,
            "win_ratio": 0 if total==0 else round((wins / total) * 100, 1),
            "category": self.get_category_display()
        }


    def __str__(self):
        return f" {self.id} - {self.name}: {self.get_category_display()}. Win-Ratio: {self.win_ratio()}"



class Match(models.Model):
    class Result(models.TextChoices):
        ABSOLUTE_WIN = "AW", "2-0"
        WIN = "WN", "2-1"
        DRAW = "DW", "1-1"
        LOSS = "LS", "1-2"
        ABSOLUTE_LOSS = "AL", "0-2"

    class Meta:
        ordering = ("-date_played", )

    deck1 = models.ForeignKey(Deck, on_delete=models.CASCADE, related_name='matches_as_deck1')
    deck2 = models.ForeignKey(Deck, on_delete=models.CASCADE, related_name='matches_as_deck2')
    winner = models.ForeignKey(Deck, on_delete=models.CASCADE, related_name='matches_won', blank=True, null=True)
    result = models.CharField(choices=Result.choices, default=Result.ABSOLUTE_WIN, max_length=2)
    date_played = models.DateTimeField(auto_now_add=True)

    def clean(self):
        """
         Ensure that:
         - A deck cannot play against itself.
         - The winner corresponds with the result.
         """
        if self.deck1 == self.deck2:
            raise ValidationError("A deck cannot compete against itself.")

        # If result is not DRAW, winner must be either deck1 or deck2 based on result
        if self.result == self.Result.DRAW:
            if self.winner is not None:
                raise ValidationError("There must be no winner for a draw.")
        elif self.result in [self.Result.ABSOLUTE_WIN, self.Result.WIN] and self.winner != self.deck1:
            raise ValidationError("Deck1 must be the winner for result 2-0 or 2-1.")
        elif self.result in [self.Result.ABSOLUTE_LOSS, self.Result.LOSS] and self.winner != self.deck2:
            raise ValidationError("Deck2 must be the winner for result 0-2 or 1-2.")


    def save(self, *args, **kwargs):
        if self.result in [self.Result.ABSOLUTE_WIN, self.Result.WIN]:
            self.winner = self.deck1
        elif self.result in [self.Result.ABSOLUTE_LOSS, self.Result.LOSS]:
            self.winner = self.deck2 # Deck1 wins with 2-1
        elif self.result == self.Result.DRAW:
            self.winner = None

        self.clean()

        super().save(*args, **kwargs) # We modify the save() to check the equality of decks. That's why super(), to call the father save.

        # Update stats for both decks
        self.deck1.update_stats()
        self.deck2.update_stats()


    def delete(self, *args, **kwargs):
        # When a match is deleted, update the stats of both decks and head-to-head
        super().delete(*args, **kwargs)
        self.deck1.update_stats()
        self.deck2.update_stats()

    def __str__(self):
        return f"{self.deck1.name} vs {self.deck2.name}. |-> Winner: {self.winner.name if self.winner else 'Draw'}"

    def serialize(self):
        return {
            "id": self.id,
            "deck1": self.deck1.serialize(),
            "deck2": self.deck2.serialize(),
            "date_played": self.date_played.date(),
            "winner": self.winner.name if self.winner else None,
            "result": self.get_result_display(),
        }





mtg/forms.py
from django import forms

mtg/views.py
import json
from sqlite3 import IntegrityError

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse

from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import User, Deck, Match
from .services import process_login


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request, "mtg/index.html", {
            "user": request.user
        })
    else:
        return HttpResponseRedirect(reverse("mtg:login"))


def login_view(request):
    if request.method == "POST":
        user, password = process_login(request)

        if user:
            user = authenticate(request, username=user.username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse("mtg:index"))
        else:
            return render(request, "mtg/login.html", {
                "message": "Invalid credentials."
            })
    else:
        return render(request, "mtg/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("mtg:index"))


def register(request):
    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]

        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        if password != confirmation:
            return render(request, "mtg/register.html", {
                "message": "Passwords must match."
            })

        try:
            user = User.objects.create_user(name, email, password)
            user.save()
        except IntegrityError:
            return render(request, "mtg/register.html", {
                "message": "User with that email already exists."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("mtg:index"))
    else:
        return render(request, "mtg/register.html")


@login_required
def get_decks(request):
    decks = Deck.objects.all()
    return JsonResponse([deck.serialize() for deck in decks], safe=False)


@login_required
def get_deck_by_id(request, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    return JsonResponse(deck.serialize(), safe=False)


@login_required
def get_decks_by_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    decks = Deck.objects.filter(user=user)

    decks_sorted = sorted(decks, key= lambda deck: (deck.win_ratio(), deck.total_matches_count), reverse=True)
    decks_data = [deck.serialize() for deck in decks_sorted]

    no_user_decks = Deck.objects.exclude(user=user)
    no_user_decks_data = [deck.serialize() for deck in no_user_decks]

    return JsonResponse({
        "decks": decks_data,
        "no_user_decks": no_user_decks_data,
        "user": user.serialize()
    }, safe=False)


@login_required
def get_user_by_id(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return JsonResponse(user.serialize(), safe=False)


@login_required
def get_logged_in_user(request):
    return JsonResponse({
        "name": request.user.username,
        "id": request.user.id})


@login_required
def get_results(request):
    matches = Match.objects.all()
    match_data = [match.serialize() for match in matches][:10]

    best_player = json.loads(get_best_n_players(request, n=1).content.decode())
    best_player_data = best_player[0] if best_player else {}

    best_deck = json.loads(get_best_n_decks(request, n=1).content.decode())
    best_deck_data = best_deck[0] if best_deck else {}

    return JsonResponse({
        "matches": match_data,
        "best_player": best_player_data,
        "best_deck": best_deck_data,
        }, safe=False)


@login_required
def get_results_by_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    matches = Match.objects.filter(user=user)
    matches_data = [match.serialize() for match in matches]
    return JsonResponse({
        "matches": matches_data,
        "user": user.serialize(),
    }, safe=False)


def get_best(request):
    _type = request.GET.get("type", None)
    n = int(request.GET.get("n", 1))

    if _type == "deck":
        return get_best_n_decks(request, n)
    elif _type == "player":
        return get_best_n_players(request, n)
    else:
        return JsonResponse({"error": "Invalid Type"}, status=400)


def get_best_n_players(request, n=1):
    players = User.objects.all()
    sorted_players = sorted(players, key=lambda p: (p.win_ratio(), p.total_played()), reverse=True)
    best_n_players = sorted_players[:n]

    return JsonResponse([best.serialize() for best in best_n_players], safe=False)


@login_required
def get_best_n_decks(request, n=5, user_id=None):
    decks = Deck.objects.filter(user=user_id) if user_id else Deck.objects.all()
    sorted_decks = sorted(decks, key=lambda deck: (deck.win_ratio(), deck.total_matches_count), reverse=True)
    best_decks = sorted_decks[:n]

    return JsonResponse([best.serialize() for best in best_decks],safe=False)


@login_required
def get_options(request, _type="result"):
    if _type == "result":
        decks = get_decks_by_user(request=request, user_id=request.user.id)
        decks_decoded = json.loads(decks.content.decode())
        user_decks, rival_decks = decks_decoded["decks"], decks_decoded["no_user_decks"]

        # Format Match.Result.choices for JSON response
        results_match = [{"id": choice[0], "label": choice[1]} for choice in Match.Result.choices]

        return JsonResponse({
            "decks": user_decks,
            "rival_decks": rival_decks,
            "results_match": results_match,
        }, safe=False)

    elif _type == "deck":
        category = [{"id": choice[0], "label": choice[1]} for choice in Deck.Category.choices]
        return JsonResponse({"category": category}, safe=False)

    else:
        return JsonResponse({"error": "Invalid Type"}, status=400)


@login_required
def add_match(request):
    if request.method == "POST":
        deck1_id = request.POST["deck1"]
        result_code = request.POST["result"]
        deck2_id = request.POST["deck2"]

        print(deck1_id, result_code, deck2_id)

        # Validate required fields
        if not all([deck1_id, deck2_id, result_code]):
            return JsonResponse({"error": "All fields are required."}, status=400)

        # Fetch Deck objects and ensure they are valid
        deck1 = get_object_or_404(Deck, id=deck1_id)
        deck2 = get_object_or_404(Deck, id=deck2_id)

        new_match = Match.objects.create(deck1=deck1, deck2=deck2, result=result_code)
        new_match.save()
        return JsonResponse({"message": "Match added successfully", "match_id": new_match.id})


@login_required
def add_deck(request):
    if request.method == "POST":
        deck_name = request.POST["name"]
        category = request.POST["category"]

        print(deck_name, category)

        if not all([deck_name, category]):
            return JsonResponse({"error": "All fields are required."}, status=400)

        new_deck = Deck.objects.create(user=request.user, name=deck_name, category=category)
        new_deck.save()

        return JsonResponse({"message": "Deck added successfully", "deck_id": new_deck.id})

mtg/templates/mtg/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MTG - Results</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
    <link rel="stylesheet" href="{% static 'mtg/css/styles.css' %}">
</head>
<body class="index-page fixed-background">
    <div id="App"></div>

    <!-- Components -->
    <script type="text/babel" src="{% static 'mtg/js/components/RenderNavbar.jsx' %}"></script>
    <script type="text/babel" src="{% static 'mtg/js/components/RenderDeck.jsx' %}"></script>
    <script type="text/babel" src="{% static 'mtg/js/components/RenderPlayer.jsx' %}"></script>
    <script type="text/babel" src="{% static 'mtg/js/components/RenderResults.jsx' %}"></script>
    <script type="text/babel" src="{% static 'mtg/js/components/RenderBestDecks.jsx' %}"></script>
    <script type="text/babel" src="{% static 'mtg/js/App.jsx' %}"></script>

    <script type="text/babel">
            ReactDOM.render(<App />, document.querySelector("#App"));
    </script>
</body>
</html>

mtg/templates/mtg/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}MTG{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'mtg/css/styles.css' %}">
        <meta name="description" content="App to track Magic The Gathering results while displaying stats">
        <meta name="keywords" content="MTG, results, statistics">
        <meta name="author" content="Alvaro Juan Gomez">
        <meta name="viewport" content="width=device-width">
        {% block script %}
        {% endblock %}
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <header>

        </header>
        <main>
            {% block body %}
            {% endblock %}
        </main>
        <footer>

        </footer>
    </body>
</html>

mtg/templates/mtg/login.html
{% extends "mtg/layout.html" %}

{% block body_class %}fixed-background login-page{% endblock %}

{% block body %}
    <div class="container-fluid d-flex justify-content-center align-items-center vh-100">
        <div class="form-container p-4">
            <h2 class="text-center">Login</h2>

            {% if message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}

            <form action="{% url 'mtg:login' %}" method="post" class="mt-4">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control" type="text" name="name_or_email" placeholder="Name/Email" required>
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Login</button>
            </form>

            <p class="text-center mt-3">Don't have an account?
                <a href="{% url 'mtg:register' %}">Register here.</a>
            </p>
        </div>
    </div>
{% endblock %}

mtg/templates/mtg/register.html
{% extends "mtg/layout.html" %}

{% block body_class %}fixed-background register-page{% endblock %}

{% block body %}
    <div class="container-fluid d-flex justify-content-center align-items-center vh-100">
        <div class="form-container p-4">
            <h2 class="text-center">Register</h2>

            {% if message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}

            <form action="{% url 'mtg:register' %}" method="post" class="mt-4">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="name" placeholder="Name" required>
                </div>
                <div class="form-group">
                    <input class="form-control" type="email" name="email" placeholder="Email Address" required>
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password" required>
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Register</button>
            </form>

            <p class="text-center mt-3">
                Already have an account?
                <a href="{% url 'mtg:login' %}">Log In here.</a>
            </p>
        </div>
    </div>
{% endblock %}